#pragma once 

#define POOL_COUNT "pool_count"
#define MODE "mode"
#define SPECIAL "special"
#define NAMES1 "names1"
#define NAMES2 "names2"
#define NAMES3 "names3"
#define NAMES4 "names4"
#define OVERLAY1 "overlay1"
#define OVERLAY2 "overlay2"
#define OVERLAY3 "overlay3"
#define OVERLAY4 "overlay4"

#define NAME_COLOR "name_color"
#define NAME_COLOR_6_STAR "name_color_6_star"
#define TEXTB "text_b"
#define TEXTG "text_g"
#define TEXTR "text_r"
#define TEXTA "text_a"

#define OFF_MUSIC "off_music"
#define INWINDOW "in_window"
#define OFF_VIDEO "off_video"
#define USE_VIDEO_BACKGROUND "use_video_background"
#define NOSMOOTHUI "no_smooth_ui"

#define FLOATWINDOW "float_window_switch"
#define FLOAT_WINDOW_WIDTH "float_window_width"
#define FLOAT_WINDOW_HEIGHT "float_window_height"
#define FLOAT_WINDOW_X "float_window_x"
#define FLOAT_WINDOW_Y "float_window_y"
#define FLOAT_WINDOW_IMG "float_window_img"

#define WINDOW_WIDTH "window_width"
#define WINDOW_HEIGHT "window_height"
#define WINDOW_X "window_x"
#define WINDOW_Y "window_y"
#define VERTICAL_SYNC "vertical_sync"
#define WINDOW_TITLE "window_title"

#define BACKGROUND_IMG_PATH "background_img_path"
#define IMGS_PATH "imgs_path"
#define VIDEO_BACKGROUND_PATH "video_background_path"
#define DEFAULT_FONT_PATH "default_font_path"
#define ICON_FONT_PATH "icon_font_path"
#define VIDEO_BACKGROUND_PATH "video_background_path"
#define CLICK_MUSIC_PATH "click_music_path"
#define ENTER_MUSIC_PATH "enter_music_path"
#define BACKGROUND_MUSIC_PATH "background_music_path"
#define BGM_PATH BACKGROUND_MUSIC_PATH

#define DEBUG "debug"
#define SHOW_FPS "show_fps"