#pragma once
#include "config.h"

#define YUANSHI L"Diamond"
#define NAMES1 L"namesfile1"
#define NAMES2 L"namesfile2"
#define NAMES3 L"namesfile3"
#define NAMES4 L"namesfile4"
#define BLUE_BALL_COUNT L"buleball"
#define PINK_BALL_COUNT L"redball"
#define OFF_VIDEO L"off video"
#define WINDOW_TITLE L"title name"
#define MODE L"firstmode"
#define INWINDOW L"window mode(not full screen)"
#define POOL_COUNT L"pool counts"
#define IMAGE_DIRECTORY L"ImageDirectory"
#define OVER4 L"over4"
#define OVER3 L"over3"
#define OVER2 L"over2"
#define OVER1 L"over1"
#define SPECIAL L"special"
#define OFFMUSIC L"off music"
#define SIGNALSTAR3 L"signal 3star video"
#define SIGNALSTAR4 L"signal 4star video"
#define SIGNALSTAR5 L"signal 5star video"
#define GROUPSTAR4 L"group 4star video"
#define GROUPSTAR5 L"group 5star video"
#define FLOATWINDOW L"open float window"
#define FLOATPHOTO L"float window picture"
#define FLOATX L"float window x"
#define FLOATY L"float window y"
#define FLOATW L"float window width"
#define FLOATH L"float window height"
#define MU L"float window Mu"
#define TEXTR L"text red"
#define TEXTG L"text green"
#define TEXTB L"text blue"
#define NOSETTINGFILE L"cancel setting json file"
#define UNSUITFONT L"the new font is unsuit"
#define DEBUG L"debug mode"
#define TYPICAL L"typical mode"
#define FPS L"fps"
#define MEM L"small memory"