name: Build

on:
  push:
    branches: [ main, master, openGL ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master, openGL ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # Windows x64
          - os: windows-latest
            arch: x64
            c_compiler: cl
            cpp_compiler: cl
            vcpkg_triplet: x64-windows-static-release

         # Windows ARM64
          - os: windows-11-arm
            arch: arm64
            c_compiler: cl
            cpp_compiler: cl
            vcpkg_triplet: arm64-windows-static-release
         # Windows x86
          - os: windows-latest
            arch: x86
            c_compiler: cl
            cpp_compiler: cl
            vcpkg_triplet: x86-windows-static

          # Linux x64
          - os: ubuntu-latest
            arch: x64
            c_compiler: gcc
            cpp_compiler: g++
            vcpkg_triplet: x64-linux-release
          
          # Linux ARM64 (需要自托管 runner)
          - os: ubuntu-24.04-arm
            arch: arm64
            c_compiler: gcc
            cpp_compiler: g++
            vcpkg_triplet: arm64-linux-release
            use_system_deps: true

          # macOS x64
          - os: macos-13  # Intel-based
            arch: x64
            c_compiler: clang
            cpp_compiler: clang++
            vcpkg_triplet: x64-osx-release
          
          # macOS ARM64 (Apple Silicon)
          - os: macos-latest  # M1/M2-based
            arch: arm64
            c_compiler: clang
            cpp_compiler: clang++
            vcpkg_triplet: arm64-osx-release

    env:
      VCPKG_TARGET_TRIPLET: ${{ matrix.vcpkg_triplet }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
        # Windows 专用步骤
    - name: Setup MSVC Environment
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch }}
        vs-version: latest

    - name: Setup Windows Build Tools
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        where cl
        where link
        cl /? >nul 2>&1 && echo "MSVC compiler found" || echo "MSVC compiler NOT found"

    - name: Setup build environment
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Linux" ]]; then
          # 更新包管理器
          sudo apt-get update
          
          # 安装基础构建工具
          sudo apt-get install -y \
            build-essential \
            cmake \
            ninja-build \
            pkg-config \
            git \
            curl \
            zip \
            unzip \
            tar
          
          # 安装多媒体相关工具
          sudo apt-get install -y \
            nasm \
            yasm
          
          # 安装 autotools 套件
          sudo apt-get install -y \
            autoconf \
            automake \
            autotools-dev \
            libtool \
            libltdl-dev \
            gettext \
            flex \
            bison \
            gperf
          
          # 安装开发库
          sudo apt-get install -y \
            libx11-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev \
            libgl1-mesa-dev \
            libasound2-dev \
            python3-dev \
            python3-setuptools \
            libibus-1.0-dev \
            libwayland-dev libxkbcommon-dev libegl1-mesa-dev \
            libx11-dev libxft-dev libxext-dev
            
        elif [[ "${{ runner.os }}" == "macOS" ]]; then
          brew install \
            nasm \
            yasm \
            ninja \
            autoconf \
            automake \
            libtool \
            gettext \
            pkg-config
        elif [[ "${{ runner.os }}" == "Windows" ]]; then
          # Windows 通常不需要额外安装，但可以安装 Ninja 作为备选
          choco install ninja -y || true
        fi

    - name: Cache vcpkg
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/build/vcpkg-installed
        key: vcpkg-${{ runner.os }}-${{matrix.arch}}-${{ hashFiles('**/vcpkg.json') }}
        restore-keys: |
          vcpkg-${{ runner.os }}-${{matrix.arch}}-${{ hashFiles('**/vcpkg.json') }}

    - name: Cache Download
      uses: actions/cache@v4
      with:
        path: |
          C:/vcpkg/downloads
          ~/.cache/vcpkg
        key: vcpkg
        restore-keys: |
          vcpkg

    - name: Configure CMake
      shell: bash
      run: |
        if [[ "${{ matrix.use_system_deps }}" == "true" ]]; then
          cmake -B build -S . \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
            -DVCPKG_TARGET_TRIPLET=${{ env.VCPKG_TARGET_TRIPLET }} \
            -DUSE_SYSTEM_DEPS=ON\
            -G Ninja
        else
          cmake -B build -S . \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
            -DVCPKG_TARGET_TRIPLET=${{ env.VCPKG_TARGET_TRIPLET }} \
            -G Ninja
        fi

    - name: Build
      shell: bash
      run: |
        cd build
        cmake --build . --config Release --parallel 4

    - name: Debug Build Output
      shell: bash
      run: |
        echo "=== Complete build directory listing ==="
        find build -type f | sort
        
        echo "=== Binary files ==="
        find build -type f -exec file {} \; | grep -i "executable\|mach-o\|elf"
        
        echo "=== Checking specific paths ==="
        ls -la build/ || true
        ls -la build/bin/ || true
        ls -la build/Release/ || true
        ls -la build/Debug/ || true

    - name: Create Archive (Debug Version)
      shell: bash
      run: |
        mkdir -p ~/installer_files

        if( [[ "${{ runner.os }}" == "Windows" ]] ); then
          cp -r build/bin/Release/*.exe ~/installer_files/
          cp -r build/bin/Release/*.dll ~/installer_files/
          cp -r build/bin/Release/files ~/installer_files/
        else
          cp -r build/bin/* ~/installer_files/
        fi
        
        cd ~/installer_files
        ls -la
        
        tar -czf ~/random_name_${{ matrix.arch }}_${{ runner.os }}.tar.gz *

    - name: Create Installer
      if: matrix.os == 'windows-latest' || matrix.os == 'windows-11-arm'
      env: 
        GITHUB_ACTIONS: true
        SOURCE_DIR: ~/installer_files
        INSTALLER_DIR: ~/installer/Output
        ARCH: ${{ matrix.arch }}
      shell: pwsh
      run: |
        iscc installer_action\common.iss
      continue-on-error: true

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: random_name_${{ matrix.arch }}_${{ runner.os }}
        path: ~/random_name_${{ matrix.arch }}_${{ runner.os }}.tar.gz
        retention-days: 30

    - name: Upload Installer
      if: matrix.os == 'windows-latest' || matrix.os == 'windows-11-arm'
      uses: actions/upload-artifact@v4
      with:
        name: random_name_${{ matrix.arch }}_${{ matrix.os }}_installer
        path: ~/installer/Output/*.exe
        retention-days: 30

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ~/random_name_${{ matrix.arch }}_${{ matrix.os }}.tar.gz
          ~/installer/Output/*.exe
        pre-release: true
        make_latest: false
        name: Release action ${{ github.ref_name }}
        body: |
          Release from github actions
          This is a pre-release for the current build.
          - Commit: ${{ github.sha }}
          - Changes: ${{ github.event.head_commit.message }}
        tag_name: action${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}