name: Build for Multiple Platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        platform: ['x64', 'x86','arm64']

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg integrate install

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore dependencies
      run: .\vcpkg\vcpkg install

    - name: Build Solution for matrix.platform
      run: |
        msbuild /m /p:Configuration=Release /p:Platform="{{ matrix.platform }}" random.sln

    - name: Package Artifact for matrix.platform
      run: |
        $artifactName = "YourArtifact_{{ matrix.platform }}"
        Compress-Archive -Path .\YourProject\bin\Release\{{ matrix.platform }}\* -DestinationPath $artifactName
        echo "ARTIFACT_NAME=$artifactName" >> $env:GITHUB_ENV

    - name: Upload Artifact for {{ matrix.platform }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.ARTIFACT_NAME }}
