name: Build for Multiple Platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 60  # 设置超时时间为60分钟

    strategy:
      matrix:
        platform: ['x64', 'x86', 'arm64']

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat

    - name: Setup MSBuild——安装 MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore dependencies
      run: |
        set VCPKG_FEATURE_FLAGS=manifests,static
        .\vcpkg\vcpkg integrate install
        .\vcpkg\vcpkg install

    - name: Build Solution for ${{ matrix.platform }}
      run: |
        msbuild /m /p:Configuration=Release /p:RuntimeLibrary=MultiThreaded /p:Platform=${{ matrix.platform }} /p:VcpkgTriplet=${{ matrix.platform }}-windows /p:VcpkgEnabled=true /p:VcpkgRoot=.\vcpkg random.sln

    - name: Package Artifact for ${{ matrix.platform }}
      run: |
        $artifactName = "YourArtifact_${{ matrix.platform }}"
        Compress-Archive -Path .\YourProject\bin\Release\${{ matrix.platform }}\* -DestinationPath $artifactName
        echo "ARTIFACT_NAME=$artifactName" >> $env:GITHUB_ENV

    - name: Upload Artifact for ${{ matrix.platform }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.ARTIFACT_NAME }}
