name: Build for Multiple Platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 60  # 设置超时时间为60分钟

    strategy:
      matrix:
        platform: ['x64','x86','arm64']

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat

    - name: Setup MSBuild——安装 MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore dependencies
      env:
        VCPKG_FEATURE_FLAGS: manifests,static
        VCPKG_CRT_LINKAGE: static
        VCPKG_LIBRARY_LINKAGE: static
        VCPKG_DEFAULT_TRIPLET: ${{ matrix.platform }}-windows-static
      run: |
        set VCPKG_FEATURE_FLAGS=manifests
        .\vcpkg\vcpkg integrate install
        pwd

    - name: Build Solution for ${{ matrix.platform }}
      env:
        VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      run: |
        msbuild /m /p:Configuration=Release /p:RuntimeLibrary=MultiThreaded /p:Platform=${{ matrix.platform }} random.sln

    - name: Package Artifact for ${{ matrix.platform }}
      run: |
        $outputPath = "${{ github.workspace }}\${{ matrix.platform }}\Release"
        $filesPath = "${{ github.workspace }}\files"
        if (Test-Path $outputPath) {
          Compress-Archive -Path $outputPath\*, $filesPath\* -DestinationPath "${{ matrix.platform }}.zip"
          echo "ARTIFACT_NAME=${{ matrix.platform }}.zip" >> $env:GITHUB_ENV
        } else {
          Write-Error "The path '$outputPath' does not exist."
          exit 1
        }
    - name: Upload Artifact for ${{ matrix.platform }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.ARTIFACT_NAME }}
